version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devlog_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devlog
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
